### PR TITLE
Update log4net example for compatibility with v6

### LINKED ISSUE #123: log4net.rst is broken
Activated and Preparing dont exist any more

### PR DESCRIPTION
**Pull request by alistairjevans**
I implemented the log4net example 'properly', following v6 patterns.

So we have log4net middleware, and a module that adds middleware to every registration.

Fixes #123

### CODE REVIEW

**Review by tillig — APPROVED** [review]
It didn't occur to me how very different this is. Not sure if the folks following this pattern will immediately understand the breaking change here; I'll add a link to this doc from the breaking changes section of the release notes once it's rendered.

**Comment by VassilSanych** [comment]
MiddlewareModule from the sample is not compatible with builder.RegisterModule<...>

**Comment by alistairjevans** [comment]
How so? I can do the following, and I get all the logging behaviour I expect:

```csharp
var builder = new ContainerBuilder();
builder.RegisterModule(new MiddlewareModule(new Log4NetMiddleware()));

builder.RegisterType<Service1>();

var container = builder.Build();

var instance = container.Resolve<Service1>();
```

**Comment by VassilSanych** [comment]
This is not belong dependency type injection. You just create the module in place.

**Comment by alistairjevans** [comment]
I'm sorry, I do not understand; you'll need to give me an example of what you mean.

**Comment by VassilSanych** [comment]
For example, you cannot use this with RegisterAssemblyModules.

**Comment by VassilSanych** [comment]
```
public class Log4NetModule : MiddlewareModule<Log4NetMiddleware> {}

public abstract class MiddlewareModule<T> : Module where T : IResolveMiddleware, new()
{
		private readonly IResolveMiddleware _middleware;
		public MiddlewareModule()
		{
			_middleware = new T();
		}
		protected override void AttachToComponentRegistration(IComponentRegistryBuilder componentRegistryBuilder,
			IComponentRegistration registration)
		{
			// Attach to the registration's pipeline build.
			registration.PipelineBuilding += (sender, pipeline) =>
			{
				// Add our middleware to the pipeline.
				pipeline.Use(_middleware);
			};
		}
	}
```
it will be better as it seems to me

**Comment by alistairjevans** [comment]
For the simple module example in the docs it works though. If you in particular need a variant to make it work with RegisterAssemblyModules, then so be it, but that doesn't belong in the docs.

**Pull request merged**
